# Installer
FROM node:16-alpine as INSTALLER

# Caching
# RUN apk add --no-cache libc6-compat

WORKDIR /app

RUN apk update && \
    apk upgrade && \
    apk add git

RUN npm install -g @types/node \
    && npm install -g typescript@4.3.5 

COPY . .

RUN npm install --force
##########################

# BUILDER
FROM node:16-alpine as BUILDER

RUN npm i -g turbo
COPY --from=INSTALLER . .

WORKDIR /app

##########################

# APP
FROM node:16-alpine as APP

WORKDIR /app

RUN apk update && \
    apk upgrade && \
    apk add git

COPY --from=BUILDER /app/apps/admin/src ./src
COPY --from=BUILDER /app/apps/admin/public ./public
COPY --from=BUILDER /app/node_modules ./node_modules
COPY --from=BUILDER /app/packages ./packages
COPY --from=BUILDER /app/package.json ./package.json

ENV DEBIAN_FRONTEND=noninteractive
ENV DISABLE_ESLINT_PLUGIN=true
ENV ESLINT_NO_DEV_ERRORS=true
ENV SKIP_PREFLIGHT_CHECK=true

LABEL author="Tolfix" maintainer="support@tolfix.com"

EXPOSE 3000

CMD ["react-scripts", "start"]
