# Installer
FROM node:16-alpine as INSTALLER

# Caching
RUN apk add --no-cache libc6-compat

WORKDIR /app

RUN apk update && \
    apk upgrade && \
    apk add git

RUN npm install -g @types/node \
    && npm install -g typescript@4.3.5 

COPY . .

RUN npm install --force
##########################

# BUILDER
FROM node:16-alpine as BUILDER

RUN npm i -g turbo
COPY --from=INSTALLER . .

WORKDIR /app

RUN tsc --project apps/api/tsconfig.json
##########################

# APP
FROM node:16-alpine as APP

WORKDIR /app

RUN apk update && \
    apk upgrade && \
    apk add git

COPY --from=BUILDER /app/apps/api/build ./build
COPY --from=BUILDER /app/node_modules ./node_modules
COPY --from=BUILDER /app/packages ./packages
COPY --from=BUILDER /app/package.json ./package.json

ENV DEBIAN_FRONTEND=noninteractive

LABEL author="Tolfix" maintainer="support@tolfix.com"

ENV PLUGINS "[]"
ENV DISABLE_JSON_ERROR "true"

EXPOSE 3001

CMD [ "node", "./build/Main.js" ]
