# Installer
FROM node:16-alpine as INSTALLER

# Caching
# RUN apk add --no-cache libc6-compat

WORKDIR /app

RUN apk update && \
    apk upgrade && \
    apk add git

RUN npm install -g @types/node \
    && npm install -g typescript@4.3.5 

COPY . .

RUN npm install --force
##########################

# BUILDER
FROM node:16-alpine as BUILDER


RUN npm i -g turbo
COPY --from=INSTALLER . .
WORKDIR /app
# Print our directory
RUN ls -la
RUN turbo run build --scope=cpg-api
##########################

# APP
FROM node:16-alpine as APP

WORKDIR /app

RUN apk update && \
    apk upgrade && \
    apk add git

COPY --from=BUILDER /app/apps/customer ./
COPY --from=BUILDER /app/node_modules ./node_modules
COPY --from=BUILDER /app/packages ./packages
COPY --from=BUILDER /app/package.json ./package.json

COPY ./apps/customer/entrypoint.sh .
COPY ./apps/customer/.env.production .

LABEL author="Tolfix" maintainer="support@tolfix.com"

RUN apk add --no-cache --upgrade bash
RUN chmod +x /app/entrypoint.sh
ENTRYPOINT ["/app/entrypoint.sh"]

RUN addgroup -g 1001 -S nodejs
RUN adduser -S nextjs -u 1001
RUN chown -R nextjs:nodejs /app/.next

USER nextjs

EXPOSE 3000
ENV PORT 3000

RUN npx next telemetry disable

CMD npm run start
