name: Docker Image - Admin

on:
  push:
    paths:
      - "apps/admin/src/**"
      - "apps/admin/public/**"
      - "apps/admin/package.json"
      - "apps/admin/Dockerfile"
    branches:
      - master
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Docker login
        env:
          DOCKER_USER: ${{secrets.DOCKER_USERNAME}}
          DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
        run: |
          docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
      
      # Build for master branch (development builds)
      - name: Build and push development Docker image
        if: github.event_name == 'push'
        run: |
          docker build . --file ./apps/admin/Dockerfile --tag tolfixorg/cpg-admin:build-${{github.run_number}}
          docker push tolfixorg/cpg-admin:build-${{github.run_number}}
      
      # Build for release tags
      - name: Build and push release Docker image
        if: github.event_name == 'release'
        run: |
          TAG_NAME=${GITHUB_REF#refs/tags/}
          docker build . --file ./apps/admin/Dockerfile --tag tolfixorg/cpg-admin:${TAG_NAME} --tag tolfixorg/cpg-admin:latest
          docker push tolfixorg/cpg-admin:${TAG_NAME}
          docker push tolfixorg/cpg-admin:latest
